import { createScreenshotSelector } from "content/translate_triggers/screenshot/selector.js";

describe("screenshot selector", () => {
    beforeEach(() => {
        document.documentElement.innerHTML = "<head></head><body></body>";
        chrome.i18n.getMessage.mockReturnValue("Select an area");
    });

    afterEach(() => {
        chrome.i18n.getMessage.mockReset();
    });

    it("consumes the click generated by finishing a capture selection", async () => {
        const selector = createScreenshotSelector();
        const selectionPromise = selector.start();
        const overlay = document.getElementById("edge-translate-screenshot-overlay");

        overlay.dispatchEvent(createMouseEvent("mousedown", 10, 20));
        overlay.dispatchEvent(createMouseEvent("mouseup", 80, 120));

        expect(document.getElementById("edge-translate-screenshot-overlay")).toBe(overlay);

        const clickEvent = createMouseEvent("click", 80, 120);
        const dispatchResult = overlay.dispatchEvent(clickEvent);

        expect(dispatchResult).toBe(false);
        expect(clickEvent.defaultPrevented).toBe(true);

        await expect(selectionPromise).resolves.toMatchObject({
            rect: {
                left: 10,
                top: 20,
                width: 70,
                height: 100,
            },
            position: [10, 20],
        });
        expect(document.getElementById("edge-translate-screenshot-overlay")).toBeNull();
    });
});

function createMouseEvent(type, clientX, clientY) {
    return new MouseEvent(type, {
        bubbles: true,
        cancelable: true,
        button: 0,
        clientX,
        clientY,
    });
}
