const OCR_LANGUAGES = [
    { code: "afr", label: "Afrikaans", aliases: ["南非语", "南非荷兰语"] },
    { code: "amh", label: "Amharic", aliases: ["阿姆哈拉语"] },
    { code: "ara", label: "Arabic", aliases: ["阿拉伯语"] },
    { code: "asm", label: "Assamese", aliases: ["阿萨姆语"] },
    { code: "aze", label: "Azerbaijani", aliases: ["阿塞拜疆语"] },
    { code: "aze_cyrl", label: "Azerbaijani - Cyrillic", aliases: ["阿塞拜疆语 西里尔"] },
    { code: "bel", label: "Belarusian", aliases: ["白俄罗斯语"] },
    { code: "ben", label: "Bengali", aliases: ["孟加拉语"] },
    { code: "bod", label: "Tibetan", aliases: ["藏语"] },
    { code: "bos", label: "Bosnian", aliases: ["波斯尼亚语"] },
    { code: "bul", label: "Bulgarian", aliases: ["保加利亚语"] },
    { code: "cat", label: "Catalan; Valencian", aliases: ["加泰罗尼亚语", "瓦伦西亚语"] },
    { code: "ceb", label: "Cebuano", aliases: ["宿务语"] },
    { code: "ces", label: "Czech", aliases: ["捷克语"] },
    {
        code: "chi_sim",
        label: "Chinese - Simplified",
        aliases: ["中文", "简体中文", "简中", "汉语", "普通话"],
    },
    { code: "chi_tra", label: "Chinese - Traditional", aliases: ["繁体中文", "繁中", "中文繁体"] },
    { code: "chr", label: "Cherokee", aliases: ["切罗基语"] },
    { code: "cym", label: "Welsh", aliases: ["威尔士语"] },
    { code: "dan", label: "Danish", aliases: ["丹麦语"] },
    { code: "deu", label: "German", aliases: ["德语"] },
    { code: "dzo", label: "Dzongkha", aliases: ["宗卡语"] },
    { code: "ell", label: "Greek, Modern (1453-)", aliases: ["希腊语", "现代希腊语"] },
    { code: "eng", label: "English", aliases: ["英语", "英文"] },
    { code: "enm", label: "English, Middle (1100-1500)", aliases: ["中古英语"] },
    { code: "epo", label: "Esperanto", aliases: ["世界语"] },
    { code: "est", label: "Estonian", aliases: ["爱沙尼亚语"] },
    { code: "eus", label: "Basque", aliases: ["巴斯克语"] },
    { code: "fas", label: "Persian", aliases: ["波斯语"] },
    { code: "fin", label: "Finnish", aliases: ["芬兰语"] },
    { code: "fra", label: "French", aliases: ["法语"] },
    { code: "frk", label: "German Fraktur", aliases: ["德语 Fraktur", "德语哥特体"] },
    { code: "frm", label: "French, Middle (ca. 1400-1600)", aliases: ["中古法语"] },
    { code: "gle", label: "Irish", aliases: ["爱尔兰语"] },
    { code: "glg", label: "Galician", aliases: ["加利西亚语"] },
    { code: "grc", label: "Greek, Ancient (-1453)", aliases: ["古希腊语"] },
    { code: "guj", label: "Gujarati", aliases: ["古吉拉特语"] },
    { code: "hat", label: "Haitian; Haitian Creole", aliases: ["海地语", "海地克里奥尔语"] },
    { code: "heb", label: "Hebrew", aliases: ["希伯来语"] },
    { code: "hin", label: "Hindi", aliases: ["印地语"] },
    { code: "hrv", label: "Croatian", aliases: ["克罗地亚语"] },
    { code: "hun", label: "Hungarian", aliases: ["匈牙利语"] },
    { code: "iku", label: "Inuktitut", aliases: ["因纽特语"] },
    { code: "ind", label: "Indonesian", aliases: ["印尼语", "印度尼西亚语"] },
    { code: "isl", label: "Icelandic", aliases: ["冰岛语"] },
    { code: "ita", label: "Italian", aliases: ["意大利语"] },
    { code: "ita_old", label: "Italian - Old", aliases: ["古意大利语"] },
    { code: "jav", label: "Javanese", aliases: ["爪哇语"] },
    { code: "jpn", label: "Japanese", aliases: ["日语", "日文"] },
    { code: "kan", label: "Kannada", aliases: ["卡纳达语"] },
    { code: "kat", label: "Georgian", aliases: ["格鲁吉亚语"] },
    { code: "kat_old", label: "Georgian - Old", aliases: ["古格鲁吉亚语"] },
    { code: "kaz", label: "Kazakh", aliases: ["哈萨克语"] },
    { code: "khm", label: "Central Khmer", aliases: ["高棉语", "柬埔寨语"] },
    { code: "kir", label: "Kirghiz; Kyrgyz", aliases: ["吉尔吉斯语"] },
    { code: "kor", label: "Korean", aliases: ["韩语", "朝鲜语", "韩文"] },
    { code: "kur", label: "Kurdish", aliases: ["库尔德语"] },
    { code: "lao", label: "Lao", aliases: ["老挝语"] },
    { code: "lat", label: "Latin", aliases: ["拉丁语"] },
    { code: "lav", label: "Latvian", aliases: ["拉脱维亚语"] },
    { code: "lit", label: "Lithuanian", aliases: ["立陶宛语"] },
    { code: "mal", label: "Malayalam", aliases: ["马拉雅拉姆语"] },
    { code: "mar", label: "Marathi", aliases: ["马拉地语"] },
    { code: "mkd", label: "Macedonian", aliases: ["马其顿语"] },
    { code: "mlt", label: "Maltese", aliases: ["马耳他语"] },
    { code: "msa", label: "Malay", aliases: ["马来语"] },
    { code: "mya", label: "Burmese", aliases: ["缅甸语"] },
    { code: "nep", label: "Nepali", aliases: ["尼泊尔语"] },
    { code: "nld", label: "Dutch; Flemish", aliases: ["荷兰语", "佛兰芒语"] },
    { code: "nor", label: "Norwegian", aliases: ["挪威语"] },
    { code: "ori", label: "Oriya", aliases: ["奥里亚语"] },
    { code: "pan", label: "Panjabi; Punjabi", aliases: ["旁遮普语"] },
    { code: "pol", label: "Polish", aliases: ["波兰语"] },
    { code: "por", label: "Portuguese", aliases: ["葡萄牙语"] },
    { code: "pus", label: "Pushto; Pashto", aliases: ["普什图语"] },
    { code: "ron", label: "Romanian; Moldavian; Moldovan", aliases: ["罗马尼亚语", "摩尔多瓦语"] },
    { code: "rus", label: "Russian", aliases: ["俄语"] },
    { code: "san", label: "Sanskrit", aliases: ["梵语"] },
    { code: "sin", label: "Sinhala; Sinhalese", aliases: ["僧伽罗语"] },
    { code: "slk", label: "Slovak", aliases: ["斯洛伐克语"] },
    { code: "slv", label: "Slovenian", aliases: ["斯洛文尼亚语"] },
    { code: "spa", label: "Spanish; Castilian", aliases: ["西班牙语"] },
    { code: "spa_old", label: "Spanish; Castilian - Old", aliases: ["古西班牙语"] },
    { code: "sqi", label: "Albanian", aliases: ["阿尔巴尼亚语"] },
    { code: "srp", label: "Serbian", aliases: ["塞尔维亚语"] },
    { code: "srp_latn", label: "Serbian - Latin", aliases: ["塞尔维亚语 拉丁"] },
    { code: "swa", label: "Swahili", aliases: ["斯瓦希里语"] },
    { code: "swe", label: "Swedish", aliases: ["瑞典语"] },
    { code: "syr", label: "Syriac", aliases: ["叙利亚语"] },
    { code: "tam", label: "Tamil", aliases: ["泰米尔语"] },
    { code: "tel", label: "Telugu", aliases: ["泰卢固语"] },
    { code: "tgk", label: "Tajik", aliases: ["塔吉克语"] },
    { code: "tgl", label: "Tagalog", aliases: ["塔加洛语", "菲律宾语"] },
    { code: "tha", label: "Thai", aliases: ["泰语"] },
    { code: "tir", label: "Tigrinya", aliases: ["提格里尼亚语"] },
    { code: "tur", label: "Turkish", aliases: ["土耳其语"] },
    { code: "uig", label: "Uighur; Uyghur", aliases: ["维吾尔语"] },
    { code: "ukr", label: "Ukrainian", aliases: ["乌克兰语"] },
    { code: "urd", label: "Urdu", aliases: ["乌尔都语"] },
    { code: "uzb", label: "Uzbek", aliases: ["乌兹别克语"] },
    { code: "uzb_cyrl", label: "Uzbek - Cyrillic", aliases: ["乌兹别克语 西里尔"] },
    { code: "vie", label: "Vietnamese", aliases: ["越南语"] },
    { code: "yid", label: "Yiddish", aliases: ["意第绪语"] },
];

const OCR_LANGUAGE_CODES = OCR_LANGUAGES.map((item) => item.code);

export { OCR_LANGUAGES, OCR_LANGUAGE_CODES };
