import { createScreenshotSelector } from "content/select/select_screenshot.js";

describe("screenshot selector", () => {
    let originalDialogClose;
    let originalDialogShowModal;

    beforeEach(() => {
        document.documentElement.innerHTML = "<head></head><body></body>";
        chrome.i18n.getMessage.mockReturnValue("Select an area");
        originalDialogClose = HTMLDialogElement.prototype.close;
        originalDialogShowModal = HTMLDialogElement.prototype.showModal;
    });

    afterEach(() => {
        chrome.i18n.getMessage.mockReset();
        restoreDialogMethod("close", originalDialogClose);
        restoreDialogMethod("showModal", originalDialogShowModal);
    });

    it("opens the capture overlay as a modal dialog when supported", async () => {
        const { close, showModal } = mockDialogMethods();
        const selector = createScreenshotSelector();
        const selectionPromise = selector.start();
        const overlay = document.getElementById("edge-translate-screenshot-overlay");

        expect(overlay.tagName).toBe("DIALOG");
        expect(showModal).toHaveBeenCalledTimes(1);
        expect(showModal.mock.contexts[0]).toBe(overlay);

        overlay.dispatchEvent(createMouseEvent("mousedown", 10, 20));
        overlay.dispatchEvent(createMouseEvent("mouseup", 80, 120));
        overlay.dispatchEvent(createMouseEvent("click", 80, 120));

        await expect(selectionPromise).resolves.toMatchObject({
            rect: {
                left: 10,
                top: 20,
                width: 70,
                height: 100,
            },
        });
        expect(close).toHaveBeenCalledTimes(1);
    });

    it("consumes the click generated by finishing a capture selection", async () => {
        const selector = createScreenshotSelector();
        const selectionPromise = selector.start();
        const overlay = document.getElementById("edge-translate-screenshot-overlay");

        overlay.dispatchEvent(createMouseEvent("mousedown", 10, 20));
        overlay.dispatchEvent(createMouseEvent("mouseup", 80, 120));

        expect(document.getElementById("edge-translate-screenshot-overlay")).toBe(overlay);

        const clickEvent = createMouseEvent("click", 80, 120);
        const dispatchResult = overlay.dispatchEvent(clickEvent);

        expect(dispatchResult).toBe(false);
        expect(clickEvent.defaultPrevented).toBe(true);

        await expect(selectionPromise).resolves.toMatchObject({
            rect: {
                left: 10,
                top: 20,
                width: 70,
                height: 100,
            },
            position: [10, 20],
        });
        expect(document.getElementById("edge-translate-screenshot-overlay")).toBeNull();
    });

    it("cancels a modal capture session without letting the dialog close itself", async () => {
        const { close } = mockDialogMethods();
        const selector = createScreenshotSelector();
        const selectionPromise = selector.start();
        const overlay = document.getElementById("edge-translate-screenshot-overlay");

        const cancelEvent = new Event("cancel", { bubbles: true, cancelable: true });
        const dispatchResult = overlay.dispatchEvent(cancelEvent);

        expect(dispatchResult).toBe(false);
        expect(cancelEvent.defaultPrevented).toBe(true);
        await expect(selectionPromise).resolves.toBeNull();
        expect(close).toHaveBeenCalledTimes(1);
        expect(document.getElementById("edge-translate-screenshot-overlay")).toBeNull();
    });

    it("keeps the capture overlay visible when modal dialogs are unavailable", async () => {
        replaceDialogMethod("showModal", undefined);
        const selector = createScreenshotSelector();
        const selectionPromise = selector.start();
        const overlay = document.getElementById("edge-translate-screenshot-overlay");

        expect(overlay.open).toBe(true);

        overlay.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));
        window.dispatchEvent(new KeyboardEvent("keydown", { key: "Escape" }));

        await expect(selectionPromise).resolves.toBeNull();
        expect(document.getElementById("edge-translate-screenshot-overlay")).toBeNull();
    });
});

function mockDialogMethods() {
    const showModal = jest.fn(function showModalMock() {
        this.open = true;
    });
    const close = jest.fn(function closeMock() {
        this.open = false;
    });

    replaceDialogMethod("close", close);
    replaceDialogMethod("showModal", showModal);
    return { close, showModal };
}

function replaceDialogMethod(name, value) {
    Object.defineProperty(HTMLDialogElement.prototype, name, {
        configurable: true,
        value,
    });
}

function restoreDialogMethod(name, value) {
    if (typeof value === "function") {
        replaceDialogMethod(name, value);
        return;
    }

    delete HTMLDialogElement.prototype[name];
}

function createMouseEvent(type, clientX, clientY) {
    return new MouseEvent(type, {
        bubbles: true,
        cancelable: true,
        button: 0,
        clientX,
        clientY,
    });
}
